modLoader="javafml"
loaderVersion="[61,)"
license="LGPLv3"
issueTrackerURL="https://github.com/CorgiTaco-MC/CorgiLib/issues"
[[mods]]
modId="corgilib"
version="${version}" #mandatory
displayName="CorgiLib" #mandatory
displayURL="https://github.com/CorgiTaco/CorgiLib" #optional
logoFile="assets/corgilib/corgilib.png" #optional
authors="Corgi Taco"
credits="Joseph T. McQuigg (JT122406)"
description='''
Library with handy utilities.
'''

[[dependencies.corgilib]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[61,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.corgilib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.11,)"
    ordering="NONE"
    side="BOTH"
